<template>
  <AppLayout>
    <div class="p-6 max-w-5xl mx-auto">
      <h1 class="text-2xl font-bold text-deep-ocean mb-4">Affiliate Program Overview</h1>
      <p class="text-gray-600 mb-8">Complete legal framework and operational structure for the Company's Affiliate Commission Program.</p>
      
      <!-- Legal Document Style Content -->
      <div class="bg-white rounded-lg border border-gray-200 shadow-sm p-8 space-y-8">
        
        <!-- Header -->
        <div class="text-center border-b border-gray-200 pb-6">
          <h2 class="text-xl font-bold text-deep-ocean mb-2">Affiliate Commissions Structure – Legal Overview</h2>
        </div>

        <!-- Section 1 -->
        <section>
          <h3 class="text-lg font-semibold text-deep-ocean mb-3">1. Program Overview</h3>
          <p class="text-gray-700 leading-relaxed">
            The Company offers an Affiliate Program ("Program") under which eligible participants ("Affiliates") may earn commissions for referring new users and promoting Company products or services. Participation is voluntary and subject to these Terms & Conditions.
          </p>
        </section>

        <!-- Section 2 -->
        <section>
          <h3 class="text-lg font-semibold text-deep-ocean mb-3">2. Commission Structure</h3>
          <p class="text-gray-700 leading-relaxed mb-4">
            Affiliates are compensated under a multi-tiered commission plan. Commissions are calculated as a percentage of the Net Revenue generated by referred users, as defined below:
          </p>
          <ul class="list-disc list-inside text-gray-700 space-y-2 ml-4 mb-4">
            <li><strong>Direct Referral Commission:</strong> Paid when an Affiliate directly refers a new subscriber.</li>
            <li><strong>Downline Commission (Multi-Level):</strong> Paid on sales generated by referrals made by an Affiliate's network, up to three (3) levels deep.</li>
            <li><strong>Leadership Bonuses:</strong> Paid when Affiliates qualify for higher tiers based on personal referrals and team growth.</li>
            <li><strong>President Group:</strong> Operates independently, with enhanced commissions and bonuses.</li>
          </ul>
          
          <div class="bg-gray-50 rounded-lg p-4 mt-4">
            <h4 class="font-semibold text-gray-800 mb-4">Official Commission Structure:</h4>
            
            <!-- President Level -->
            <div class="mb-4 p-3 border-l-4 border-purple-500 bg-white rounded-r">
              <h5 class="font-bold text-purple-700 text-sm mb-2">PRESIDENT</h5>
              <p class="text-sm text-gray-700 mb-1">
                <strong>Commissions:</strong> Direct Referral 25% | 1st Generation 15% | 2nd Generation 10% | 3rd Generation 5% | Leadership Bonus 10%
              </p>
              <p class="text-xs text-gray-600">
                <strong>Upgrade Conditions:</strong> Directly Refer 50 People, 100 Downlines
              </p>
            </div>

            <!-- Influencer Level -->
            <div class="mb-4 p-3 border-l-4 border-indigo-500 bg-white rounded-r">
              <h5 class="font-bold text-indigo-700 text-sm mb-2">INFLUENCER</h5>
              <p class="text-sm text-gray-700 mb-1">
                <strong>Commissions:</strong> Direct Referral 20% | 1st Generation 12% | 2nd Generation 7% | 3rd Generation 3% | Leadership Bonus 7%
              </p>
              <p class="text-xs text-gray-600">
                <strong>Upgrade Conditions:</strong> Directly Refer 20 People, 50 Downlines
              </p>
            </div>

            <!-- Leader Level -->
            <div class="mb-4 p-3 border-l-4 border-blue-500 bg-white rounded-r">
              <h5 class="font-bold text-blue-700 text-sm mb-2">LEADER</h5>
              <p class="text-sm text-gray-700 mb-1">
                <strong>Commissions:</strong> Direct Referral 18% | 1st Generation 10% | 2nd Generation 5% | 3rd Generation 2% | Leadership Bonus 5%
              </p>
              <p class="text-xs text-gray-600">
                <strong>Upgrade Conditions:</strong> Directly Refer 10 People, 30 Downlines
              </p>
            </div>

            <!-- Promoter Level -->
            <div class="mb-4 p-3 border-l-4 border-green-500 bg-white rounded-r">
              <h5 class="font-bold text-green-700 text-sm mb-2">PROMOTER</h5>
              <p class="text-sm text-gray-700 mb-1">
                <strong>Commissions:</strong> Direct Referral 15% | 1st Generation 7% | 2nd Generation 3%
              </p>
              <p class="text-xs text-gray-600">
                <strong>Upgrade Conditions:</strong> Directly Refer 5 People, 10 Downlines
              </p>
            </div>

            <!-- Reader Level -->
            <div class="mb-4 p-3 border-l-4 border-yellow-500 bg-white rounded-r">
              <h5 class="font-bold text-yellow-700 text-sm mb-2">READER</h5>
              <p class="text-sm text-gray-700 mb-1">
                <strong>Commissions:</strong> Direct Referral 12% | 1st Generation 5%
              </p>
              <p class="text-xs text-gray-600">
                <strong>Upgrade Conditions:</strong> Directly Refer 3 People, Each Consuming 1680
              </p>
            </div>

            <!-- Subscriber Level -->
            <div class="mb-4 p-3 border-l-4 border-orange-500 bg-white rounded-r">
              <h5 class="font-bold text-orange-700 text-sm mb-2">SUBSCRIBER</h5>
              <p class="text-sm text-gray-700 mb-1">
                <strong>Commissions:</strong> Direct Referral 10%
              </p>
              <p class="text-xs text-gray-600">
                <strong>Upgrade Conditions:</strong> Directly Refer 1 Person Consuming 1680
              </p>
            </div>

            <!-- Fan Level -->
            <div class="mb-4 p-3 border-l-4 border-gray-400 bg-white rounded-r">
              <h5 class="font-bold text-gray-600 text-sm mb-2">FAN</h5>
              <p class="text-sm text-gray-700 mb-1">
                <strong>Commissions:</strong> No Commission
              </p>
              <p class="text-xs text-gray-600">
                <strong>Upgrade Conditions:</strong> Starting Level
              </p>
            </div>

            <p class="text-xs text-gray-600 mt-4 pt-3 border-t border-gray-300">
              <strong>Important Notes:</strong> "Direct referral" refers to personally enrolled users. "Generation" refers to levels in your downline network. Leadership bonuses apply to qualifying levels. President group operates independently with enhanced benefits.
            </p>
          </div>
        </section>

        <!-- Section 3 -->
        <section>
          <h3 class="text-lg font-semibold text-deep-ocean mb-3">3. Qualification & Advancement</h3>
          <ul class="list-disc list-inside text-gray-700 space-y-2 ml-4">
            <li>Advancement through tiers is contingent upon meeting referral and downline requirements, which may include:</li>
            <li class="ml-4">Minimum number of direct referrals.</li>
            <li class="ml-4">Minimum downline participants or subscribers.</li>
            <li class="ml-4">Compliance with Program Rules.</li>
            <li>The Company reserves the right to review qualification criteria periodically.</li>
          </ul>
        </section>

        <!-- Section 4 -->
        <section>
          <h3 class="text-lg font-semibold text-deep-ocean mb-3">4. Payment of Commissions</h3>
          <ul class="list-disc list-inside text-gray-700 space-y-2 ml-4">
            <li>Commissions are tracked electronically through the Company's platform.</li>
            <li>Payments are made in [currency/USDT/company token], subject to minimum payout thresholds.</li>
            <li>Commissions are paid net of refunds, chargebacks, and transaction fees.</li>
            <li>The Company may withhold or offset commissions for suspected fraud, policy violations, or unpaid balances.</li>
          </ul>
        </section>

        <!-- Section 5 -->
        <section>
          <h3 class="text-lg font-semibold text-deep-ocean mb-3">5. Legal & Compliance Considerations</h3>
          <ul class="list-disc list-inside text-gray-700 space-y-2 ml-4">
            <li><strong>Independent Contractor:</strong> Affiliates are not employees, agents, or partners of the Company.</li>
            <li><strong>No Guarantee of Income:</strong> Participation does not guarantee commissions or profits.</li>
            <li><strong>Anti-Pyramid Compliance:</strong> The Program is based on actual product/service sales. Compensation is tied to legitimate transactions, not mere recruitment.</li>
            <li><strong>Tax Responsibility:</strong> Affiliates are responsible for reporting and paying all applicable taxes on earned commissions.</li>
            <li><strong>Right to Amend:</strong> The Company may amend the Commission Structure at its discretion, with notice to Affiliates.</li>
          </ul>
        </section>

        <!-- Call to Action -->
        <div class="bg-blue-50 border border-blue-200 rounded-lg p-6 mt-8">
          <div class="flex items-start space-x-3">
            <svg class="w-6 h-6 text-blue-600 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
            <div>
              <h4 class="font-semibold text-blue-800 mb-1">Next Steps</h4>
              <p class="text-sm text-blue-700 mb-3">Review the detailed commission breakdown and qualification requirements to understand your earning potential.</p>
              <router-link 
                :to="$route.path.startsWith('/admin') ? '/admin/training/commissions' : '/training/commissions'"
                class="inline-flex items-center px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 transition-colors"
              >
                View Commission Details
                <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                </svg>
              </router-link>
            </div>
          </div>
        </div>
      </div>
    </div>
  </AppLayout>
</template>

<script setup>
import AppLayout from '../components/layouts/AppLayout.vue'
</script>

<style scoped>
</style>
